### ISSUE TITLE
"mnicmp is slightly problematic" - how so?

### ISSUE THREAD

**Issue by scruss** [ratboy666/la36#1]
Any way I can make the font less problematic for you?

**Comment by ratboy666** [comment]
la36 converts overprint to bold, and does underline. mnicmp is very close to the dec la36, but bold and underline do not match when used in xterm. I'll get some screen captures for you...

**Comment by scruss** [comment]
Could the LA36 do bold? You might have been able to print a little darker by overstriking using backspaces. The bold on my font is roughly how later dot matrix printers worked, by shifting half a pin width. I'm almost entirely sure that the LA36 couldn't do that. I was never striving for perfect accuracy: my font has additional glyphs that the LA36 never had.

Similarly for underlines: unless I did something very clever with OTF tables that (I don't yet understand|may not be possible|wouldn't be supported outside very specialized applications anyway), you're going to get system underbars, not dots. Again, backspaces between characters interspersed with `_` characters is the period-correct way of doing this. I wouldn't be surprised if somewhere in xterm's settings there was a way of enabling underlining via backspacing

**Comment by ratboy666** [comment]
Stewart

The LA36 program emulates part of what the terminal did.

If a sequence like:
ABC<return> B <return> is seen (or backspaces)

A (bold B)C is displayed. Using xterm attributes.

Similar, if _ is used, the underscore attribute is applied. but... with
mnicmp, the underscore is not in the correct location. (the attribute
doesn't match).

Also, LA36 program does strike-out with -, converting that to the
attribute.

When I get some cycles (likely tomorrow) I'll get some screen shots to
illustrate. I wrote LA36 because I wanted a vintage terminal, without
the wear and
tear.

More coming.

And.. thanks for the font! It does look great!

Fred Weigel

**Comment by scruss** [comment]
There's no other location for mnicmp's underscore to be, though.

It might make your depiction better if you uninstalled mnicmp Bold, too

**Comment by ratboy666** [comment]
> Any way I can make the font less problematic for you?

And... here are the pictures - in order:using svbasic, monaco and mnicmp

![using-svbasic](https://user-images.githubusercontent.com/7596496/199774697-af24f529-1199-430a-abfb-2a81afc7b715.png)
![using-monaco](https://user-images.githubusercontent.com/7596496/199774743-a09837f9-e234-4823-926c-4cbb1e60c550.png)
![using-mnicmp](https://user-images.githubusercontent.com/7596496/199774770-ac97970b-c744-4eb8-8dc9-e722cbbe75bc.png)

As you can see, with mnicmp, the strikethrough is at the underline position, and the underline is... way down. Note that neither monaco nor sv-basic suffer from this. mnicmp is usable, *including bold*

These were captured by running la36 -d /dev/rfcomm0 But, all this is with xterm -- the commands are:

xterm -fa Monaco -fs 16 (for 1920x1080) --fa mnicmp -fs 20 and -fa SV Basic Manual -fs 16

the actual command to select a font is done inside of xterm -- eg.

ESC ]50;mnicmp:size=20 BEL

with font ops enabled on the xterm call.

I don't know if the font baseline in mnicmp can be adjusted  -- I don't know anything about font formats.  But, the baseline does not compare to Monaco or SV Basic at all. And that is what I mean by "slightly problematic". la36 is trying to be an emulation of a printing terminal (la36). Note that all la36 is doing is overprint analysis and conversion to character properties.

Note that the discrepancy between _ as an attribute and _ as a character is almost 1/2 the character height! - is a bit better. I *could* fix that, by converting _ to space with underscore attribute, and - to space with strikethrough. That would take care of the bulk of the issue, ...but... is still would look a bit yucky. Bold is ok!

I hope this clarifies -- sorry for the delay -- la36 and other things vintage computing is just a hobby: not my day job.

**Comment by ratboy666** [comment]
Stewart

Also, I generate these by using la36 to communicate with my Altair-Duino, as a terminal. I just use "^H" (control-h) to do
backspace, and then the overtype character. I can generate examples with any character strings you want... let me know.

la36 is really just a toy... and it works well enough. If you cannot adjust the baseline, I will just use the _ and - to attribute trick for the mnicmp font. I don't think I can "micro-adjust" the baseline in xterm. And... I never wanted to write a terminal emulator... I leave that to xterm -- and just concentrated on the "make it look like paper". So, no GUI code, either!

Thanks enormously for your interest!

Fred Weigel

**Comment by scruss** [comment]
Okay, I see what's happening. The DECwriter II had no descenders at all (take a look at lower case `q`). It had 7 vertical pin positions. The underline character can't go any lower than the lowest dots of regular characters. The `-` character you're using for strikethrough is one dot below the top of lower case characters. **These are in the correct positions for the DECwriter II in mnicmp**

```
       .......          .......          .......  
       .......          .......          .......  
       .......          #.#.#..          .......  
       #.#.#.#          #..#..#          .......  
       .......          #..#..#          .......  
       .......          #..#..#          .......  
       .......          #..#..#          #.#.#.#  
```


The solution to this problem is to turn off bold, overstrike and underline, as the DECwriter II didn't support them. We only started to get descenders and underlines rather crudely with 9-pin printers, and the much later 18 and 24-pin printers made them look vaguely acceptable. Sometimes the historically accurate solution of ‘*can't even do it, don't even try*’ can be very freeing.
